Repository UK-Export-Finance/estore-api, pull requests merged in 2023-09, with the labels that each got.

#254 feat(APIM-580): remove input field exporterName if it is not required
  src/modules/sharepoint/sharepoint.service.test.ts
  src/modules/sharepoint/sharepoint.service.ts
  src/modules/site-buyer/buyer-folder-creation.service.test.ts
  src/modules/site-buyer/buyer-folder-creation.service.ts
  src/modules/site-buyer/dto/create-buyer-folder-request.dto.ts
  src/modules/site-deal/deal-folder-creation.service.test.ts
  src/modules/site-deal/deal-folder-creation.service.ts
  src/modules/site-deal/dto/create-deal-folder-request.dto.ts
  src/modules/site-deal/dto/create-facility-folder-request.dto.ts
  src/modules/site-deal/facility-folder-creation.service.test.ts
  src/modules/site-deal/site-deal.controller.create-deal-folder.test.ts
  src/modules/site-deal/site-deal.controller.ts
  src/modules/site/site.service.create-site.test.ts
  src/modules/site/site.service.get-site-status-by-exporter-name.test.ts
  src/modules/site/site.service.ts
  test/docs/__snapshots__/get-docs.api-test.ts.snap
  test/site-buyer/post-site-buyers.api-test.ts
  test/site-deal/post-site-deal-facilities.api-test.ts
  test/site-deal/post-site-deals.api-test.ts
  test/support/generator/create-buyer-folder-generator.ts
  test/support/generator/create-deal-folder-generator.ts
  test/support/generator/create-facility-folder-generator.ts
Labels: Type: Chore

#292 fix (APIM-482): changed status from 400 to 201 in situation where Buyer, Deal or Facility folder exists
  src/modules/site-buyer/buyer-folder-creation.service.test.ts
  src/modules/site-buyer/buyer-folder-creation.service.ts
  src/modules/site-deal/deal-folder-creation.service.test.ts
  src/modules/site-deal/deal-folder-creation.service.ts
  src/modules/site-deal/facility-folder-creation.service.test.ts
  src/modules/site-deal/facility-folder-creation.service.ts
  test/site-buyer/post-site-buyers.api-test.ts
  test/site-deal/post-site-deal-facilities.api-test.ts
  test/site-deal/post-site-deals.api-test.ts
Labels: Type: Bug

#325 fix(spellcheck): added spellcheck to the pipeline
  .github/workflows/sca.yml
  .husky/commit-msg
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Type: Feature
