Repository UK-Export-Finance/estore-api, pull requests merged in 2023-07, with the labels that each got.

#104 fix(env-variable): updated envrionment variables
  .env.sample
  .github/workflows/deployment.yml
  .github/workflows/test.yml
  docker-compose.yml
  package-lock.json
  test/support/environment-variables.ts
Labels: infrastructure

#105 fix(deployment): removed syntax error
  .github/workflows/deployment.yml
Labels: infrastructure

#106 fix(deployment): syntax error
  .github/workflows/deployment.yml
Labels: infrastructure

#134 chore(deps): deps updates
  package-lock.json
Labels: Type: Chore

#135 chore(dockerfile): version updates
  Dockerfile
  docker-compose.yml
  package-lock.json
Labels: Type: Security

#142 feat(APIM-561): restrict upload file in deal folder endpoint to only use files from dtfs deal folder
  .env.sample
  .github/workflows/deployment.yml
  .github/workflows/test.yml
  docker-compose.yml
  src/config/dtfs-storage.config.ts
  src/constants/examples.constant.ts
  src/modules/deal-folder/dto/upload-file-in-deal-folder-request.dto.ts
  src/modules/dtfs-storage-client/dtfs-storage-client.service.ts
  test/docs/__snapshots__/get-docs.api-test.ts.snap
  test/support/environment-variables.ts
  test/support/generator/random-value-generator.ts
  test/support/mocks/dtfs-storage-client.service.mock.ts
Labels: Type: Feature

#145 feat(APIM-538): add environment variable for log format
  .env.sample
  .github/workflows/deployment.yml
  .github/workflows/test.yml
  docker-compose.yml
  package-lock.json
  package.json
  src/config/app.config.test.ts
  src/config/app.config.ts
  src/main.module.ts
  test/support/environment-variables.ts
Labels: Type: Feature

#148 fix(iac): added environment variable
  .github/workflows/deployment.yml
  .gitignore
Labels: infrastructure

#150 fix(iac): ACR
  .github/workflows/deploy.sh
  Dockerfile
  package-lock.json
  package.json
Labels: infrastructure

#151 fix(iac): formatting issue
  .github/workflows/infrastructure.yml
Labels: infrastructure

#152 fix(iac): formatting issues
  .github/workflows/deployment.yml
  .github/workflows/lint.yml
  .github/workflows/sca.yml
  .github/workflows/test.yml
Labels: infrastructure

#159 fix(iac): deployment
  .github/workflows/infrastructure.yml
Labels: infrastructure

#161 chore(deps): dependencies updates
  package-lock.json
  package.json
Labels: infrastructure

#164 chore(deps): dependencies updates
  package-lock.json
  package.json
Labels: infrastructure

#167 feat(APIM-468): change how integer config values are parsed
  src/config/app.config.test.ts
  src/config/app.config.ts
  src/config/custodian.config.ts
  src/config/mdm.config.ts
  src/helpers/get-int-config.helper.test.ts
  src/helpers/get-int-config.ts
  src/helpers/regex.helper.test.ts
  test/common-tests/environment-variable-parsing-unit-tests.ts
Labels: Type: Feature

#177 feat(env): environment variables
  .env.sample
  .github/workflows/deployment.yml
  .github/workflows/test.yml
  docker-compose.yml
  package-lock.json
  package.json
  src/config/app.config.test.ts
  src/config/app.config.ts
  test/support/environment-variables.ts
Labels: infrastructure
